### PR TITLE
Added Custom Login & Recovery Fields

### PR DESCRIPTION
**Pull request by mahbd**
**Custom Login Fields:**
Now user can add custom login fields. Default login fields will be replaced by custom login fields. User can access custom fields value like this:
```
onLogin: (LoginData data) async {
    Map<String, String>? customLogin = data.customLoginData;
    debugPrint('$keyName: ${customLogin[keyName]');
    .....
}
```

**Custom recover Fields:**
Now user can add custom recover fields. Default login fields will be replaced by custom recover fields. User can access custom fields value like this:
```
onRecoverPasswordCustom: (RecoverData data) async {
    debugPrint('$keyName:: ${data.customRecoverData![keyname]}');
    .....
}
```

I think in next version of flutter_login we can replace onRecoverPasswordCustom.

### CODE REVIEW

**Comment by NickB23** [comment]
This is a great addition I must add. Thanks for the PR.
Since the original fields are not presented when a customfield is added, I would suggest a userType in UserFormField as well where text is obscured with a button that could turn it into cleartext?

**Comment by mahbd** [comment]
> a userType in UserFormField as well where text is obscured with a button that could turn it into cleartext?

It will be a nice addition. I'm working on it.

**Comment by juliansteenbakker** [comment]
Thanks for your contribution!

I do think we need to look for a different solution for the `onRecoverPasswordCustom` option. It would be the best if we can merge this with `onRecoverPassword` by using RecoverData for `onRecoverPassword`. Do you think this is possible?

**Comment by mahbd** [comment]
> Thanks for your contribution!
> 
> I do think we need to look for a different solution for the `onRecoverPasswordCustom` option. It would be the best if we can merge this with `onRecoverPassword` by using RecoverData for `onRecoverPassword`. Do you think this is possible?

Yes, I think this is possible. But that will cause problem to all existing projects which are using onRecoverPassword. I think we should make such type of changes in major version. Do you plan to merge this PR in major release version?

I tried but found no idea to replace onRecoverPassword such a way that it won't cause problem to existing projects. If you have any idea, please share with me. I'll be happy to implement that.

**Pull request closed without merging**
