### PR TITLE
Added copyright line to the bottom of the page

### PR DESCRIPTION
**Pull request by poqeteer**
A simple addition of an optional line at the bottom of the page to allow for a copyright message to be added. I called the value copyright but if you like something more generic I could see that.

### CODE REVIEW

**Comment by SalahAdDin** [comment]
Up.

**Comment by juliansteenbakker** [comment]
Thank you for your contribution. I like the idea, but i am thinking about if there is a better more generic name for it. Do you have any suggestions?

**Comment by SalahAdDin** [comment]
> Thank you for your contribution. I like the idea, but i am thinking about if there is a better more generic name for it. Do you have any suggestions?

May it be _disclaimer_?

**Comment by alr2413** [comment]
@juliansteenbakker, @SalahAdDin, @poqeteer 
what if we call it _footer_?!

**Comment by SalahAdDin** [comment]
> @juliansteenbakker, @SalahAdDin, @poqeteer
> what if we call it _footer_?!

If it will contain more that a **copyright** text, it can become the generic _footer_.

**Comment by juliansteenbakker** [comment]
Footer sounds like a good one !

**Comment by juliansteenbakker** [comment]
Okay so i checked this new feature however it does not really blend in with the style that this widget is using. In order to make it something that would fit this widget it needs to blend with the style that is set by the user or the widget like for example use the same color, background and font as the title. Also the placing is not the best one either. I think it would be better to place it somewhere in the space between the Authentication card and the end of the screen. Also, there should be some kind of animation occur when the user logs in so that the text disappears in the same way and style of the other elements.

**Pull request merged**
