### PR TITLE
Added the capability of setting a RegExp to evaluate the user or email

### PR DESCRIPTION
**Pull request by WaterBlueNewWorld**
Also added the name parameter to the example in login_screen.dart and a fake user inside `users.dart` in order to test the RegExp

### CODE REVIEW

**Comment by SalahAdDin** [comment]
@WaterBlueNewWorld can you give a default value to `regexUserValidation

@juliansteenbakker What do you think about this?

**Comment by WaterBlueNewWorld** [comment]
@SalahAdDin It is already initialized, if no Regex pattern is provided when using the property `regexUserValidation` the validation function uses the default validation pattern on `regex.dart`

regex.dart
```dart
class Regex {
  // https://stackoverflow.com/a/32686261/9449426
  Regex._();
  static RegExp regExp = RegExp(r'^[^\s@]+@[^\s@]+\.[^\s@]+$');
  static set regexp(RegExp value) {
    regExp = value;
  }
  static RegExp get regexp => regExp;
}
```

flutter_login.dart
```dart
userValidator: userValidator ?? (v) {
    Regex.regexp = widget.regexUserValidation ?? Regex.regexp;
    if (v!.isEmpty || !Regex.regexp.hasMatch(v)) {
        return 'Invalid user!';
    }
    return null;
}
```

**Comment by juliansteenbakker** [comment]
Hello, thanks for your contribution. I don't understand the changes provided here. We currently have a default RegExp, but if someone wants to use their own, they could just set their own `userValidator` with a RegExp check. Am i missing something?

**Comment by SalahAdDin** [comment]
@WaterBlueNewWorld what do you think?

**Comment by juliansteenbakker** [comment]
I'm gonna close this for now as it is already possible to achieve it.

**Comment by WaterBlueNewWorld** [comment]
I didn't realize at the time, my bad and I apologize for this.

**Pull request closed without merging**
