### PR TITLE
Fix the autofill

### PR DESCRIPTION
**Pull request by jaroslawdabrowski**
The autofill has not been working. It has been fixed. Now system after login or signup asks if it should store the login details and is able to suggest login details while login.

### CODE REVIEW

**Comment by hallelk** [comment]
bump

**Comment by tas246** [comment]
This would be valuable to have.  Currently on iOS the email field does not work with autofill, the password field only fills.

**Comment by hallelk** [comment]
also in web

**Comment by jaroslawdabrowski** [comment]
@juliansteenbakker I have created this pull request and many more in last couple of weeks, can you please check those?

**Comment by juliansteenbakker** [comment]
Looks good, LGTM!

**Pull request merged**
