### PR TITLE
Ability to Remove Password Input

### PR DESCRIPTION
**Pull request by FurkanYilmaz403**
Firebase is a lot in use with Flutter. In Firebase there is an option for sign in/up with phone number and that provider doesn't take any password. And in e-commerce this is the most used provider. So there is no need to take a password, because we are authenticating with phone verification. I added an ability to remove password input just with one boolean.

### CODE REVIEW

**Comment by FurkanYilmaz403** [comment]
I am adding changes for my own project. You should just take consideration of first 9 commits.

**Comment by juliansteenbakker** [comment]
I like the idea, but i cannot merge this in its current form.

**Comment by FurkanYilmaz403** [comment]
Ok, I will edit according to current form if you'll merge it.

**Comment by Maclaon** [comment]
> Ok, I will edit according to current form if you'll merge it.

hi, is this feature megered in the current version? @FurkanYilmaz403 @juliansteenbakker , i can not find `hidePassword` in the latest version!

**Pull request closed without merging**
