### PR TITLE
bug: fixed switch-auth button not coloring correctly

### LINKED ISSUE #210: Transparent/Invisible buttons "switch to signup/login" and "go back"
**Describe the bug**
The buttons used to switch to SignUp or Login mode respectively (below the login button) as well as the "Go Back" button (below the "recovery" button) in the password forget view are transparent.  The buttons are there and react to clicks but they are not visible.

**To Reproduce**
Run the app provided in the example folder. 

**Expected behavior**
The mentioned buttons to be non-transparent.

**Screenshots**
back_button_invisible
signup_button_invisible

**Information (please complete the following information):**
 - Flutter version: [2.2.3 ]
 - Package version [2.2.2] but I also tried 2.2.1 and 2.2.0 with same behavior
 - Tested on Physical Android device and Web

### PR DESCRIPTION
**Pull request by juliansteenbakker**
fixes #210

### CODE REVIEW

**Comment by SalahAdDin** [comment]
Look:
image

I guess this one is not working.

**Comment by SalahAdDin** [comment]
Well, we have a problem here: what if we want the text to be like the primary color? Your change oberseeded mine and now we can't see the primary color, we always see black.

It totally breaks the theme.

**Comment by yogithesymbian** [comment]
https://github.com/NearHuscarl/flutter_login/issues/210#issuecomment-889897537 the go back button still white colour.

**Comment by SalahAdDin** [comment]
> [#210 (comment)](https://github.com/NearHuscarl/flutter_login/issues/210#issuecomment-889897537) the go back button still white colour.

Yeah, I saw it again.

**Pull request merged**
