### PR TITLE
Null-safety support

### LINKED ISSUE #106: Migrate to sound null safety
Description:

- Migrate to sound null safety
- Bump up package version

### PR DESCRIPTION
**Pull request by juliansteenbakker**
Fixes #106

### CODE REVIEW

**Review by lcsvcn — APPROVED** [review]

**Review by Programmer9211 — COMMENTED** [review]
Everything is ok here

**Comment by SalahAdDin** [comment]
Everything is going cool but [thise one](https://github.com/NearHuscarl/flutter_login/issues/144).

**Comment by SalahAdDin** [comment]
@juliansteenbakker My little contribution: https://github.com/NearHuscarl/flutter_login/pull/147

**Comment by surister** [comment]
What's the latest in the null safety version?

**Comment by lcsvcn** [comment]
At the moment is https://github.com/NearHuscarl/flutter_login/releases/tag/2.0.0-nullsafety.0

**Pull request merged**
