### PR TITLE
(Non breacking) : "Sign-in providers" support

### PR DESCRIPTION
**Pull request by xnio94**
now the package can show multiple Sign-in providers in addition to the email/password sign in

its not a breaking change and developers can opt not to use the feature

each Sign-in provider is represented with an icon specified by the developer and displayed in a row at the bottom of the login card

i added a new public class "LoginProvider" that have two attributes: an icon and a callback

the developers only need to provide a list of LoginProvider objects and assign it to the "loginProvidersList" attribute in the FlutterLogin widget

if the list is empty or null nothing will be shown

### CODE REVIEW

**Comment by nottmey** [comment]
Great addition! I would love to see this in the next release 👍

**Comment by lcsvcn** [comment]
@xnio94 @SalahAdDin  There is a new maintainer, we may see this PR merged soon.

**Comment by SalahAdDin** [comment]
@lcsvcn Oh, really? it is a very good news.

**Comment by iMrLopez** [comment]
Is this in prod now? if so, how can I use it?

**Comment by SalahAdDin** [comment]
@iMrLopez Yeah, it is in production now, you can follow the documentation added on this pull request or review the code, i implmente the icons and functions but I didn't test this yet.

**Pull request merged**
