### PR TITLE
Added LoginUserType to select between user EMAIL, NAME and PHONE

### PR DESCRIPTION
**Pull request by lcsvcn**
**Major adjustment:** 
 - Added `LoginUserType` to allow developers to select if they will use a **USER EMAIL**(`LoginUserType.email`), **USER NAME**(`LoginUserType.name`) or **USER PHONE**(`LoginUserType.phone`) to login in `User Field`.
 
 - `User field` is the new generic name that refers to the field above password. It can be user **email**, **name** or **phone**

 - Effect will propagate over the LoginCard, Register Card and Recover Card. The **Autofill Hints** and **Keyboard Configuration** will be adjusted accordingly.

**Minor adjustment:** 
 - Now auto-correct default value is **false**, since email, username and password should not be auto-corrected. If you need, you still can send `autocorrect: true` to AnimatedTextFormField to enable auto-correction

### CODE REVIEW

**Comment by SergeyLabutin** [comment]
Can you add Phone Number too? In Firebase and Cognito can used as user indicator out the box.

**Comment by lcsvcn** [comment]
@SergeyLabutin Yes, I can add it. I will add later this week to this PR.

**Comment by surister** [comment]
This is a must have, waiting for the merge, good job!

**Comment by lcsvcn** [comment]
Not at all. Just **AutofillHints** and **KeyboardType** will be adjusted automatically by **UserType**. 

Validation will still need to be manually implemented by developer (as before), since User Phone and User Name is not the same for every country.

The default validator is User Email Validator, since it is universal.

This was not implemented in my version, I just generalized the userField to accept Phone and Name (and act accordingly)

Check the readme for UserValidator.

**Comment by surister** [comment]
@lcsvcn could you please fix the merge issue, thanks!

**Pull request merged**
